### ISSUE TITLE
misuse of super in copyFrom

### ISSUE THREAD

**Issue by cnjmike** [slaught/antlr4-ruby#1]
at tool/resources/org/antlr/v4/tool/templates/codegen/Ruby/Ruby.stg starting at 704 
excerpt:
<if(struct.provideCopyFrom)> <! don't need copy unless we have subclasses !>
    def copyFrom(ctx)
        super.copyFrom(ctx)
        <struct.attrs:{a | self.<a.name> = ctx.<a.name>}; separator="\n">
    end

<endif>

I think you meant super(ctx).

BTW - THANK YOU !!! for this.  already having some success with it and looking forward to it being fully cooked =).

**Comment by slaught** [comment]
Thanks for catching this!

Glad you are finding it useful. I am hoping for fully cook by next week.
